#h2-secrets.yml
apiVersion: v1
kind: Secret
metadata:
name: h2-secrets
type: Opaque
data:
spring.datasource.url: jdbc:h2:file:~/test
spring.datasource.username: sa
spring.datasource.password: sa
spring.datasource.driver-class-name: org.h2.Driver